name: rent_a_car_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2  
  dio: ^5.1.0
  dio_cookie_manager: ^3.1.0
  get: ^4.6.5
  intl_phone_field: ^3.0.0
  intl: 
  lottie: ^2.3.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.4
  animated_text_kit: ^4.2.2
  nb_utils: ^5.0.8
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flutter_typeahead: ^4.6.1
  image_picker: ^0.8.4+4   
  path_provider: ^2.0.15
  flutter_cache_manager: ^3.3.1
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icon/
    - assets/lottie/
